version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: AuthDB
    volumes :
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@nomail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  redis:
    container_name: redis
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=root
    volumes:
      - redisdata:/bitnami/redis/data

volumes :
  pgdata:
  redisdata:

