server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://192.168.99.100:9411/
  cloud:
    compatibility-verifier:
      enabled: false