server:
  port: 8003

spring:
  main:
    lazy-initialization: true
  application:
    name: feedservice
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/AuthDB
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: 192.168.99.100:9092
  zipkin:
    base-url: http://192.168.99.100:9411/
  level:
    org:
      hibernate: OFF
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


